### ISSUE TITLE
add a minimal beam model

### ISSUE THREAD

**Issue by nbassler** [nbassler/TRiPddd#6]
After discussing with @grzanka. Fitting will be more robust if there is some initial width of the beam.

Propose:
- 4 mm FWHM for all beams
- 60 cm exit-window to isocenter distance
- 2 meters from last quadrupole to isocenter
- add air as material
- add exit window material
- add energy spread 1 %
- add divergence 3 mrad

**Comment by grzanka** [comment]
The 4mm FWHM - do you mean a spot size at the beam source ?
If yes, I'd mention it explicitely. Very often spot size is used as measured in water at some depth or at isocenter
